# Generated by Django 5.2.17 on 2026-09-17 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("watchlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alert_rules",
                to="watchlists.watchlist",
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="alerts.alertrule"
            ),
        ),
        migrations.AddField(
            model_name="alertcursor",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursors",
                to="alerts.alertrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertreceipt",
            constraint=models.UniqueConstraint(fields=("event", "user"), name="alert_read_unique"),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("threshold_pp__gt", 0), ("threshold_pp__lte", 100)),
                name="alert_threshold_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_minutes__in", [5, 15, 60])), name="alert_window_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("cooldown_minutes__gte", 1), ("cooldown_minutes__lte", 1440)),
                name="alert_cooldown_range",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["organization", "-created_at"], name="alert_org_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="alertevent",
            constraint=models.UniqueConstraint(
                fields=("rule", "market", "revision", "observation_id"), name="alert_event_dedup"
            ),
        ),
        migrations.AddConstraint(
            model_name="alertcursor",
            constraint=models.UniqueConstraint(
                fields=("rule", "market"), name="alert_cursor_unique"
            ),
        ),
    ]
