# Generated by Django 5.2.17 on 2026-09-15 14:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionCheckpoint",
            fields=[
                ("collector_id", models.UUIDField(primary_key=True, serialize=False)),
                ("batch_id", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("exchange_id", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("observed_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "exchange_id"), name="event_exchange_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("exchange_id", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField(db_index=True)),
                ("latest", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                ("probability_change_15m", models.FloatField(db_index=True, null=True)),
                ("volume_zscore", models.FloatField(db_index=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="markets.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exchange_id", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=20)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcomes",
                        to="markets.market",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("platform", "exchange_id"), name="market_exchange_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="outcome",
            constraint=models.UniqueConstraint(
                fields=("market", "exchange_id"), name="outcome_exchange_unique"
            ),
        ),
    ]
