# Generated by Django 5.2.17 on 2026-09-16 13:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("00000000-0000-0000-0000-000000000001"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("managed", models.BooleanField(default=False)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="ResearchTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("name_zh", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("description_zh", models.TextField(blank=True, max_length=2000)),
                ("enabled", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
                "default_permissions": ("add", "change", "view"),
            },
        ),
        migrations.CreateModel(
            name="CollectionTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("polymarket", "Polymarket"), ("kalshi", "Kalshi")], max_length=20
                    ),
                ),
                ("exchange_id", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=300)),
                ("rationale", models.TextField(max_length=2000)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targets",
                        to="markets.researchtopic",
                    ),
                ),
            ],
            options={
                "ordering": ["platform", "exchange_id", "id"],
                "default_permissions": ("add", "change", "view"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("topic", "platform", "exchange_id"),
                        name="collection_topic_target_unique",
                    )
                ],
            },
        ),
    ]
