# Generated by Django 5.2.17 on 2026-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_collectionplan_researchtopic_collectiontarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionplan',
            options={'default_permissions': ('view', 'change')},
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='controls_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='kalshi_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='kalshi_interval_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='polymarket_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='polymarket_interval_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddConstraint(
            model_name='collectionplan',
            constraint=models.CheckConstraint(condition=models.Q(('polymarket_interval_seconds__gte', 15), ('polymarket_interval_seconds__lte', 3600)), name='polymarket_poll_interval_bounds'),
        ),
        migrations.AddConstraint(
            model_name='collectionplan',
            constraint=models.CheckConstraint(condition=models.Q(('kalshi_interval_seconds__gte', 15), ('kalshi_interval_seconds__lte', 3600)), name='kalshi_poll_interval_bounds'),
        ),
    ]
