# Generated by Django 5.2.17 on 2026-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0003_collection_runtime_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCheckpoint",
            fields=[
                ("collector_id", models.UUIDField(primary_key=True, serialize=False)),
                ("page_id", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogScan",
            fields=[
                ("platform", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("observed_at", models.DateTimeField()),
                ("scan_id", models.UUIDField()),
                ("pages", models.PositiveIntegerField()),
                ("rows_seen", models.PositiveIntegerField()),
                ("accepted", models.PositiveIntegerField()),
                ("skipped", models.PositiveIntegerField()),
                ("state", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="catalog_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="catalog_interval_seconds",
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="catalog_max_pages",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="catalog_page_interval_seconds",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="coverage_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="standard_interval_seconds",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name="collectiontarget",
            name="tier",
            field=models.CharField(
                choices=[("priority", "Priority"), ("standard", "Standard")],
                default="priority",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CatalogMarket",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=20)),
                ("exchange_id", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("closes_at", models.DateTimeField(null=True)),
                ("volume_24h", models.FloatField(null=True)),
                ("volume_unit", models.CharField(max_length=20)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["platform", "status", "-volume_24h"],
                        name="catalog_platform_activity",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "exchange_id"), name="catalog_exchange_unique"
                    )
                ],
            },
        ),
    ]
