# Generated by Django 5.2.17 on 2026-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0004_market_directory_and_tiers"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collectionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("catalog_interval_seconds__gte", 300), ("catalog_interval_seconds__lte", 86400)
                ),
                name="catalog_interval_seconds_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("catalog_page_interval_seconds__gte", 5),
                    ("catalog_page_interval_seconds__lte", 300),
                ),
                name="catalog_page_interval_seconds_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("catalog_max_pages__gte", 1), ("catalog_max_pages__lte", 1000)),
                name="catalog_max_pages_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("standard_interval_seconds__gte", 60), ("standard_interval_seconds__lte", 3600)
                ),
                name="standard_interval_seconds_bounds",
            ),
        ),
    ]
