import { t } from './i18n'
import { lazy, Suspense, useRef, useState, type CSSProperties } from 'react'
import { useQuery } from '@tanstack/react-query'
import { api, type Organization } from './api'
import type { History, Market, MarketDetail, Signal } from './marketTypes'
import type { Evidence, Review, Timeline } from './researchTypes'
import { probability, change, readable, time } from './format'
import { EvidenceCard, ErrorNotice, ResearchTime } from './ResearchUI'
import { navigate, withCutoff } from './navigation'
import TerminalDialog from './TerminalDialog'
import { usePanelResize } from './terminalLayout'
import { age } from './collectionHealth'
import type { ChartViewport } from './ProbabilityChart'
import { signalValue } from './signalValue'
import AgentPanel from './AgentPanel'
const ProbabilityChart = lazy(() => import('./ProbabilityChart'))

function Skeleton({ text }: { text: string }) { return <div className="terminal-skeleton" role="status"><span /><span /><span /><p>{text}</p></div> }
function Metric({ label, value, detail, tone = '' }: { label: string; value: string; detail: string; tone?: string }) {
  return <div className="quote-metric" title={detail}><span>{label}</span><strong className={tone} key={value}>{value}</strong><small>{detail}</small></div>
}

export default function MarketWorkbench({ id, userId, organization, close, cutoff = '' }: { id: string; userId: string; organization?: Organization; close: () => void; cutoff?: string }) {
  const [hours, setHours] = useState('24')
  const [tab, setTab] = useState('signals')
  const [ledgerOpen, setLedgerOpen] = useState(false)
  const [rightTab, setRightTab] = useState('inspect')
  const [selectedSignal, setSelectedSignal] = useState<Signal | null>(null)
  const [focus, setFocus] = useState<string>()
  const [resetKey, setResetKey] = useState(0)
  const [area, setArea] = useState(true)
  const [autoScale, setAutoScale] = useState(true)
  const [selectedEvidence, setSelectedEvidence] = useState<Evidence | null>(null)
  const [expanded, setExpanded] = useState(false)
  const [search, setSearch] = useState('')
  const [pickerOpen, setPickerOpen] = useState(false)
  const [inspectorOpen, setInspectorOpen] = useState(false)
  const [signalGroup, setSignalGroup] = useState<Signal[]>([])
  const [evidenceGroup, setEvidenceGroup] = useState<Evidence[]>([])
  const viewport = useRef<ChartViewport>(null)
  const chartHeight = usePanelResize(`quanthecy.chart.v2.${userId}`, Math.min(680, Math.max(400, window.innerHeight - 460)), 360, 900, 'y')
  const [showTime, setShowTime] = useState(false)
  const suffix = cutoff ? `?cutoff=${encodeURIComponent(cutoff)}` : ''
  const detail = useQuery({ queryKey: ['market', userId, id, cutoff], queryFn: () => api<MarketDetail>(`/markets/${id}${suffix}`), refetchInterval: cutoff ? false : 30000 })
  const history = useQuery({ queryKey: ['history', userId, id, hours, cutoff], queryFn: () => {
    const end = cutoff ? new Date(cutoff) : new Date()
    const start = new Date(end.valueOf() - Number(hours) * 3600000).toISOString()
    return api<History>(`/markets/${id}/history?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end.toISOString())}&limit=10000`)
  }, refetchInterval: cutoff ? false : 60000 })
  const signals = useQuery({ queryKey: ['signals', userId, id, cutoff], queryFn: () => api<Signal[]>(`/markets/${id}/signals${suffix}`), refetchInterval: cutoff ? false : 60000 })
  const evidenceCutoff = selectedSignal?.received_at ?? cutoff
  const timeline = useQuery({ queryKey: ['terminal-timeline', userId, id, evidenceCutoff], queryFn: () => api<Timeline>(`/markets/${id}/timeline${evidenceCutoff ? `?cutoff=${encodeURIComponent(evidenceCutoff)}` : ''}`), refetchInterval: evidenceCutoff ? false : 60000 })
  const markets = useQuery({ queryKey: ['terminal-markets', userId, search], queryFn: () => api<{ items: Market[]; total: number }>(`/markets?limit=40&sort=recent&search=${encodeURIComponent(search)}`), refetchInterval: 30000 })
  const pairs = useQuery({ queryKey: ['terminal-pairs', userId, cutoff], queryFn: () => api<Review[]>(`/comparisons${suffix}`) })
  const market = detail.data
  const related = pairs.data?.filter((pair) => [pair.left_snapshot.market.id, pair.right_snapshot.market.id].includes(id)) ?? []
  function inspect(signal: Signal) { setInspectorOpen(true); setSelectedEvidence(null); setSelectedSignal(signal); setFocus(signal.received_at); setRightTab('inspect') }
  function resetFocus() { viewport.current = null; setSignalGroup([]); setEvidenceGroup([]); setSelectedEvidence(null); setSelectedSignal(null); setFocus(undefined); setResetKey((value) => value + 1) }
  const visibleSignals = signals.data?.filter((signal) => !history.data || (Date.parse(signal.received_at) >= Date.parse(history.data.start) && Date.parse(signal.received_at) <= Date.parse(history.data.end))) ?? []
  function selectSignals(items: Signal[]) { setSignalGroup(items); setEvidenceGroup([]); inspect(items.at(-1)!); setExpanded(false) }
  function selectEvidence(items: Evidence[]) { setEvidenceGroup(items); setSignalGroup([]); setSelectedEvidence(items.at(-1)!); setSelectedSignal(null); setRightTab('inspect'); setFocus(items.at(-1)!.observed_at); setInspectorOpen(true); setExpanded(false) }
  const lastWindow = market ? new Date(Math.max(Date.parse(market.last_observed_at), Date.parse(market.latest.recorded_at ?? market.last_observed_at))).toISOString() : ''
  const lastWindowLink = `#${withCutoff(`/markets/${id}`, lastWindow)}`
  const chart = market && (<section className="chart-panel"><div className="chart-toolbar"><div className="interval-switch" role="group" aria-label={t("History window")}>{[['1', '1H'], ['6', '6H'], ['24', '1D'], ['168', '7D']].map(([value, label]) => <button key={value} aria-pressed={hours === value} className={hours === value ? 'active' : ''} onClick={() => { setHours(value); resetFocus() }}>{label}</button>)}</div><div className="chart-tools"><button aria-pressed={autoScale} onClick={() => setAutoScale(!autoScale)}>{t("Auto scale")}</button><button aria-label={t("Toggle area fill")} aria-pressed={area} onClick={() => setArea(!area)}>◩</button><button onClick={resetFocus} title={t("Reset chart zoom")}>{t("Reset")}</button><button data-chart-expand aria-label={expanded ? t("Restore research panels") : t("Expand chart")} aria-pressed={expanded} onClick={() => setExpanded(!expanded)}>⛶</button></div></div>

            {history.isPending && <Skeleton text={t("Loading history…")} />}{history.error && <ErrorNotice error={history.error} retry={() => void history.refetch()} />}
            {history.data && (history.data.items.length ? <><Suspense fallback={<Skeleton text={t("Loading chart…")} />}><ProbabilityChart viewport={viewport} rows={history.data.items} signals={visibleSignals} focus={focus} onSignals={selectSignals} autoScale={autoScale} events={timeline.data?.items.map((entry) => entry.evidence)} onEvidence={selectEvidence} resetKey={resetKey} area={area} /></Suspense>{history.data.truncated && <p className="terminal-notice">{t("First 10,000 observations shown. Choose a shorter window.")}</p>}</> : <div className="chart-empty"><span>∿</span><h3>{t("No observations in this window")}</h3><p>{t("Last observed")} {time(market.last_observed_at)}.</p>{!cutoff && <a href={lastWindowLink}>{t("View last collected window →")}</a>}</div>)}
            <div className="chart-caption"><div className="chart-legend"><span><i className="legend-line" />{t("YES midpoint")}</span><span><i className="legend-diamond" />{t("Signals · 5m")}</span><span><i className="legend-news" />{t("News")}</span></div><span>{t("Local time ·")} {autoScale ? t("Auto scale (%)") : '0–100%'}</span></div>
          </section>)
  const inspector = market && (<section className="terminal-inspector" aria-label={t("Research inspector")}><div className="inspector-tabs" role="group" aria-label={t("Inspector view")}>{[['inspect', t("Overview")], ['agent', '✧ Agent'], ['rules', t("Contract")]].map(([value, label]) => <button key={value} className={rightTab === value ? 'active' : ''} aria-pressed={rightTab === value} onClick={() => setRightTab(value)}>{label}</button>)}</div><div className="inspector-body">
          {rightTab === 'agent' && <AgentPanel key={`${organization?.id}-${id}`} userId={userId} organization={organization} marketId={id} cutoff={evidenceCutoff} />}
          {rightTab === 'rules' && <><span className="micro-label">{t("SETTLEMENT & CONTRACT")}</span><h3>{t("Resolution rules")}</h3><p className="rules-text">{market.latest.market.resolution_rules || t("Rules unavailable from this source.")}</p><dl className="contract-facts"><dt>{t("Rules version")}</dt><dd>{market.latest.market.rules_version}</dd><dt>{t("Closes")}</dt><dd>{time(market.latest.market.closes_at)}</dd><dt>{t("Volume unit")}</dt><dd>{market.latest.volume?.unit ?? t("Unavailable")}</dd><dt>{t("Volume basis")}</dt><dd>{market.latest.volume?.basis ?? t("Unavailable")}</dd><dt>{t("Exchange ID")}</dt><dd>{market.exchange_id}</dd></dl></>}
          {rightTab === 'inspect' && <>
            {signalGroup.length > 1 && <div className="event-group"><strong>{signalGroup.length} {t("signals · 5-minute group")}</strong>{signalGroup.map((signal) => <button key={signal.id} aria-pressed={selectedSignal?.id === signal.id} onClick={() => inspect(signal)}>{readable(signal.signal_type)}<small>{time(signal.received_at)}</small></button>)}</div>}
            {evidenceGroup.length > 1 && <div className="event-group"><strong>{evidenceGroup.length} {t("news entries · first collected in this group")}</strong>{evidenceGroup.map((item) => <button key={item.id} aria-pressed={selectedEvidence?.id === item.id} onClick={() => { setSelectedEvidence(item); setFocus(item.observed_at) }}>{item.title}</button>)}</div>}
            <div className="panel-kicker"><span className="inspector-symbol">◎</span><div><strong>{selectedSignal ? t("Signal inspection") : t("Market overview")}</strong><small>{selectedSignal ? t("Frozen signal inputs") : t("Current research context")}</small></div></div>
            {selectedSignal ? <><span className="signal-type-badge">{readable(selectedSignal.signal_type)}</span><h3 className={`selected-change ${signalValue(selectedSignal).tone}`}>{signalValue(selectedSignal).value}</h3><p>{time(selectedSignal.received_at)}<br />{signalValue(selectedSignal).label}</p><dl className="contract-facts"><dt>{t("Spread change")}</dt><dd>{change(selectedSignal.metrics.spread_change_15m)}</dd><dt>{t("Volume z-score")}</dt><dd>{selectedSignal.metrics.volume_zscore?.toFixed(2) ?? t("Unavailable")}</dd><dt>{t("Saved observations")}</dt><dd>{selectedSignal.observation_ids.length}</dd></dl><a className="terminal-link" href={`/api/v1/signals/${selectedSignal.id}/inputs?format=csv`}>{t("Export reproducible inputs ↓")}</a><button className="text-button" onClick={resetFocus}>{t("Clear signal selection")}</button></> : <><p>{t("Track the probability, inspect unusual activity, and trace explanations to their sources.")}</p><div className="probability-gauge"><div style={{ width: `${(market.probability ?? 0) * 100}%` }} /></div><div className="gauge-labels"><span>{t("YES")} {probability(market.probability)}</span><span>100%</span></div><dl className="contract-facts"><dt>{t("Outcome")}</dt><dd>{t("YES")}</dd><dt>{t("Price basis")}</dt><dd>{t("Bid / ask midpoint")}</dd><dt>{t("Latest observed")}</dt><dd>{time(market.last_observed_at)}</dd><dt>{t("Collected since")}</dt><dd>{time(market.first_observed_at)}</dd></dl></>}
            {selectedEvidence && <div className="selected-evidence"><span className="micro-label">{t("SELECTED NEWS · FIRST AVAILABLE")} {time(selectedEvidence.observed_at)}</span><EvidenceCard item={selectedEvidence} cutoff={cutoff} /></div>}
            <button className="agent-entry" onClick={() => setRightTab('agent')}><span>✧</span><div><strong>{t("Open research analyst")}</strong><small>{t("Metrics, evidence & counter-evidence")}</small></div><span>→</span></button>
            <div className="inspector-section"><div className="terminal-panel-heading"><h3>{t("Available evidence")}</h3><span>{timeline.data?.items.length ?? '—'}</span></div>{evidenceCutoff && <p className="quiet">{t("Known by")} {time(evidenceCutoff)}</p>}{timeline.isPending && <p role="status">{t("Loading evidence…")}</p>}{timeline.error && <ErrorNotice error={timeline.error} retry={() => void timeline.refetch()} />}{timeline.data?.items.length === 0 && <p>{t("No associated evidence available at this cutoff.")}</p>}{timeline.data?.items.slice(0, 3).map(({ evidence }) => <EvidenceCard item={evidence} cutoff={evidenceCutoff} compact key={evidence.id} />)}<button className="text-button" onClick={() => { setTab('evidence'); setLedgerOpen(true); setInspectorOpen(false) }}>{t("Inspect the evidence timeline →")}</button><p className="evidence-caution">{t("Topic and timing alone do not establish a cause for a price movement.")}</p></div>
          </>}
        </div></section>)
  return <section className="market-workbench" style={{ '--chart-height': `${chartHeight.size}px` } as CSSProperties} aria-label={t("Market research terminal")}>
    <div className="terminal-breadcrumb"><button className="text-button" onClick={close}>{t("← All markets")}</button><button className="market-picker-trigger" onClick={() => setPickerOpen(true)}>{t("⌕ Switch market")}</button><button className="research-trigger" onClick={() => setInspectorOpen(true)}>{t("Research & agent ↗")}</button><div className="terminal-live"><span className={`connection-dot ${cutoff || market?.stale ? 'offline' : ''}`} />{cutoff ? t("HISTORICAL") : !market ? t("LOADING") : market.stale ? t("DELAYED") : t("REST SAMPLES")}</div></div>
    {detail.isPending && <Skeleton text={t("Loading market…")} />}{detail.error && <ErrorNotice error={detail.error} retry={() => void detail.refetch()} />}
    {market && <>
      <header className="terminal-market-header"><div className="exchange-avatar">{market.platform === 'kalshi' ? t("K") : t("P")}</div><div className="terminal-title"><div><span className="exchange-label">{market.platform}</span><span className="terminal-tag">{t(market.status)}</span><span className="terminal-tag">{t("YES")}</span></div><h2>{market.title}</h2><small>{market.exchange_id}</small></div><button className="time-toggle" aria-expanded={showTime} onClick={() => setShowTime(!showTime)}>◷ {cutoff ? t("Historical cutoff") : t("Time context")}</button></header>
      {showTime && <ResearchTime key={cutoff} cutoff={cutoff} path={`/markets/${id}`} />}
      <div className="quote-strip"><Metric label={t("YES PROBABILITY")} value={market.probability == null ? '—' : probability(market.probability)} detail={t("Bid / ask midpoint")} tone={market.probability == null || market.stale || cutoff ? '' : "positive quote-flash"} /><Metric label={t("15M CHANGE")} value={market.metrics.probability_change_15m == null ? '—' : change(market.metrics.probability_change_15m)} detail={t("Percentage points")} tone={market.metrics.probability_change_15m == null || market.stale ? '' : market.metrics.probability_change_15m < 0 ? 'negative' : 'positive'} /><Metric label={t("BEST BID / ASK")} value={`${market.best_bid == null ? '—' : probability(market.best_bid)} / ${market.best_ask == null ? '—' : probability(market.best_ask)}`} detail={t("Observed quote")} /><Metric label={t("VOLUME Z-SCORE")} value={market.metrics.volume_zscore?.toFixed(2) ?? '—'} detail={t("Sampled volume-rate z-score")} /></div>
      {market.stale && <div className="terminal-notice stale-notice" role="status"><strong>{t("Collection is stale ·")} {age(Math.max(0, Math.floor(((cutoff ? Date.parse(cutoff) : Date.now()) - Date.parse(market.last_observed_at)) / 1000)))}</strong><span>{t("Last observed")} {time(market.last_observed_at)}{t(". Quotes and changes refer to that observation.")}</span>{!cutoff && <a href={lastWindowLink}>{t("View last collected window →")}</a>}</div>}
      {!market.metrics.history_ready && <p className="terminal-notice analytics-notice">{t("Analytics pending:")} {market.metrics.reason?.replaceAll('_', ' ') ?? t("insufficient history")}. {market.stale ? t("New observations are needed before analytics can resume.") : t("A continuous 15-minute window is required.")}</p>}
      <div className="terminal-grid">
        <div className="terminal-center">
          {expanded ? <div className="chart-placeholder">{t("Chart is expanded")}</div> : chart}
          <div className="panel-resizer horizontal" aria-label={t("Chart height")} {...chartHeight.separator} />
          <section className="terminal-ledger"><div className="ledger-heading"><div className="terminal-tabs" role="tablist" aria-label={t("Market research data")}>{[['signals', t("Signals"), visibleSignals.length], ['evidence', t("News & evidence"), timeline.data?.items.length], ['comparisons', t("Related markets"), related.length], ['data', t("Data"), history.data?.items.length]].map(([value, label, count]) => <button key={value} id={`tab-${value}`} role="tab" aria-selected={tab === value} aria-controls={`panel-${value}`} tabIndex={tab === value ? 0 : -1} onKeyDown={(event) => { if (["ArrowLeft", "ArrowRight"].includes(event.key)) { event.preventDefault(); const values = ['signals', 'evidence', 'comparisons', 'data']; const next = values[(values.indexOf(tab) + (event.key === 'ArrowRight' ? 1 : 3)) % 4]; setTab(next); setLedgerOpen(true); document.getElementById(`tab-${next}`)?.focus() } }} onClick={() => { setTab(String(value)); setLedgerOpen(true) }}>{label}<span>{count ?? '—'}</span></button>)}</div><button className="ledger-toggle" aria-label={ledgerOpen ? t("Collapse activity") : t("Expand activity")} aria-expanded={ledgerOpen} aria-controls={`panel-${tab}`} onClick={() => setLedgerOpen(!ledgerOpen)}>{ledgerOpen ? '⌄' : '⌃'}</button></div>
            <div hidden={!ledgerOpen} className="ledger-body" role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`} tabIndex={0}>
              {tab === 'signals' && <>{signals.isPending && <p role="status">{t("Loading signals…")}</p>}{signals.error && <ErrorNotice error={signals.error} retry={() => void signals.refetch()} />}{!visibleSignals.length && !signals.isPending && <p className="terminal-empty">{t("No qualifying signals in this window. Select a wider range or allow more history to accumulate.")}</p>}{visibleSignals.map((signal) => <button className={`terminal-signal ${selectedSignal?.id === signal.id ? 'selected' : ''}`} key={signal.id} onClick={() => { setSignalGroup([]); inspect(signal) }}><span className={`signal-direction ${signalValue(signal).tone}`}>{signal.signal_type === 'PROBABILITY_DROP' ? '↘' : '↗'}</span><div><strong>{readable(signal.signal_type)}</strong><small>{time(signal.received_at)} · {signal.version}</small></div><span className={`signal-change ${signalValue(signal).tone}`} title={signalValue(signal).label}>{signalValue(signal).value}<small>{signal.observation_ids.length} {t("inputs")}</small></span><span className="signal-open">↗</span></button>)}</>}
              {tab === 'evidence' && <>{evidenceCutoff && <p className="selection-note">{t("Evidence known by")} {time(evidenceCutoff)}.</p>}{timeline.isPending && <p role="status">{t("Loading evidence…")}</p>}{timeline.error && <ErrorNotice error={timeline.error} retry={() => void timeline.refetch()} />}{timeline.data?.items.length === 0 && <p className="terminal-empty">{t("No associated evidence was available at this time.")}</p>}{timeline.data?.items.slice(0, 20).map(({ evidence, association }) => <div className="terminal-evidence" key={association.id}><span className="badge badge-amber">{readable(association.status)}</span><EvidenceCard item={evidence} cutoff={evidenceCutoff} compact /><button className="text-button" onClick={() => selectEvidence([evidence])}>{t("Locate when first available ↗")}</button></div>)}{(timeline.data?.truncated || (timeline.data?.items.length ?? 0) > 20) && <a className="terminal-link" href={`#${withCutoff('/evidence', evidenceCutoff)}`}>{t("Explore more evidence →")}</a>}</>}
              {tab === 'comparisons' && <>{pairs.error && <ErrorNotice error={pairs.error} retry={() => void pairs.refetch()} />}{!related.length && <p className="terminal-empty">{t("No reviewed cross-platform comparison is available for this contract.")}</p>}{related.map((pair) => <a className="terminal-pair" href={`#${withCutoff(`/comparisons/${pair.comparison_id}`, cutoff)}`} key={pair.id}><span className="badge">{readable(pair.relation)}</span><strong>{pair.title}</strong><p>{pair.differences}</p><small>{t("Inspect aligned quotes & settlement differences ↗")}</small></a>)}</>}
              {tab === 'data' && <><div className="table-scroll"><table><thead><tr><th>{t("Observed time")}</th><th>{t("YES midpoint")}</th><th>{t("Bid")}</th><th>{t("Ask")}</th><th>{t("Quality")}</th></tr></thead><tbody>{history.data?.items.slice(-30).reverse().map((row) => <tr key={row.observation_id}><td>{time(row.received_at)}</td><td>{probability(row.probability?.value)}</td><td>{probability(row.best_bid)}</td><td>{probability(row.best_ask)}</td><td>{row.quality_flags.join(', ') || t("OK")}</td></tr>)}</tbody></table></div><p className="quiet">{t("Latest 30 observations in the selected window. Volume bars show changes between compatible consecutive samples, not individual trades.")}</p>{history.data && !history.data.truncated && <div className="export-links">{['csv', 'parquet'].map((format) => <a key={format} href={`/api/v1/markets/${id}/export?format=${format}&start=${encodeURIComponent(history.data!.start)}&end=${encodeURIComponent(history.data!.end)}`}>{t("Export")} {format.toUpperCase()} ↓</a>)}</div>}</>}
            </div>
          </section>
        </div>
        <section className="market-rail" aria-label={t("Collected markets")}><div className="terminal-panel-heading"><h3>{t("Markets")}</h3><span>{markets.data?.total ?? '—'}</span></div><label className="sr-only" htmlFor="terminal-market-search">{t("Filter market sidebar")}</label><input id="terminal-market-search" placeholder={t("⌕  Filter collected markets")} value={search} onChange={(event) => setSearch(event.target.value)} /><div className="rail-columns"><span>{t("CONTRACT")}</span><span>{t("YES / 15M")}</span></div>
          {markets.isPending && <p role="status">{t("Loading markets…")}</p>}{markets.error && <ErrorNotice error={markets.error} retry={() => void markets.refetch()} />}
          <div className="market-rail-list">{markets.data?.items.map((item) => <a className={`rail-market ${item.id === id ? 'selected' : ''}`} key={item.id} href={`#/markets/${item.id}`} title={item.title} aria-current={item.id === id ? 'page' : undefined}><div><strong>{item.title}</strong><small>{item.platform} {item.stale && t("· stale")}</small></div><div><span>{item.probability == null ? '—' : probability(item.probability)}</span><small className={item.metrics.probability_change_15m == null || item.stale ? '' : item.metrics.probability_change_15m < 0 ? 'negative' : 'positive'}>{item.metrics.probability_change_15m == null ? '—' : change(item.metrics.probability_change_15m)}</small></div></a>)}</div><p className="rail-footnote">{t("Latest saved quotes ·")} {markets.data?.items.length ?? 0} {t("shown")}{cutoff ? t(" · List remains current during replay") : ''}</p>
        </section>
        <TerminalDialog open={inspectorOpen} onClose={() => setInspectorOpen(false)} title={t("Research inspector")} className={`inspector-drawer ${rightTab === 'agent' ? 'intelligence-drawer' : ''}`}>{inspector}</TerminalDialog>
      </div>
      <TerminalDialog open={expanded} onClose={() => setExpanded(false)} title={cutoff ? `${market.title} · Historical ${time(cutoff)}` : market.title} returnFocus="[data-chart-expand]" className="chart-dialog">{chart}</TerminalDialog>
      <TerminalDialog open={pickerOpen} onClose={() => setPickerOpen(false)} title={t("Switch market")} className="market-picker"><label htmlFor="market-picker-search">{t("Search collected markets")}</label><input autoFocus id="market-picker-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t("Market name…")} /><p className="quiet">{t("Latest saved quotes · Search across collected markets")}</p>{markets.isPending && <p role="status">{t("Searching…")}</p>}{markets.error && <ErrorNotice error={markets.error} retry={() => void markets.refetch()} />}{markets.data?.items.length === 0 && <p>{t("No matching markets.")}</p>}{markets.data?.items.map((item) => <a className="picker-market" key={item.id} href={`#/markets/${item.id}`} onClick={() => setPickerOpen(false)}><div><strong>{item.title}</strong><small>{item.platform} · {t(item.status)}{item.stale ? t(" · Delayed") : ''}</small></div><span>{item.probability == null ? '—' : probability(item.probability)}</span></a>)}</TerminalDialog>
      <footer className="terminal-footer"><span>{t("◉ QUANTHECY RESEARCH")}</span><span>{t("Polymarket + Kalshi · Selected binary markets")}</span><span>{t("Last observed")} {time(market.last_observed_at)}</span></footer>
      {cutoff && <button className="terminal-link" onClick={() => navigate(`/markets/${id}`)}>{t("Return to latest available data →")}</button>}
    </>}
  </section>
}
