export const qualityReasons: Record<string, string> = {
  "insufficient_history": "Insufficient continuous history",
  "sampling_gap_or_invalid_quote": "Sampling gap or excluded quality flag",
  "quality_flags_excluded": "Observation quality flag excludes research",
  "incompatible_observations": "Market, outcome or rules changed",
  "market_not_open": "Market is not open",
  "missing_resolution_rules": "Settlement rules missing",
  "invalid_recording_time": "Recorded before receipt",
  "missing_midpoint": "No valid two-sided midpoint",
  "unsupported_price_basis": "Price is not a midpoint",
  "invalid_quote": "Invalid or crossed bid/ask",
  "midpoint_mismatch": "Midpoint disagrees with bid/ask",
  "invalid_price_time": "Price timestamp is invalid or stale",
  "missing_volume": "Volume missing",
  "invalid_volume": "Invalid cumulative volume",
  "invalid_volume_time": "Volume timestamp is invalid or stale",
  "price_source_changed": "Price source changed in window",
  "volume_basis_changed": "Volume unit or basis changed",
  "volume_counter_reset": "Cumulative volume counter reset",
  "constant_volume_baseline": "Volume baseline has no variation",
  "invalid_volume_rate": "Invalid volume change rate",
  "future_observation": "Observation timestamp is in the future",
  "stale_price": "Price is older than 180 seconds",
  "stale_observation": "No observation in the past 180 seconds",
  "quality_not_evaluated": "Awaiting current quality policy",
  "analytics_pending": "New quote awaits window analysis",
  "conflicting_duplicate": "Conflicting copies of the same observation",
  "history_truncated": "History query exceeded its bound",
  "invalid_stored_observation": "Stored observation failed schema validation",
  "source_time_missing": "Exchange timestamp unavailable; receipt time used",
  "liquidity_unavailable": "Liquidity depth unavailable"
}
