# Generated by Django 5.2.17 on 2026-09-16 04:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfiguration",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.CharField(default="openai_compatible", max_length=30),
                ),
                (
                    "base_url",
                    models.URLField(default="https://api.openai.com/v1", max_length=500),
                ),
                ("model", models.CharField(blank=True, max_length=160)),
                ("encrypted_api_key", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("daily_run_limit", models.PositiveIntegerField(default=10)),
                ("max_output_tokens", models.PositiveIntegerField(default=2000)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(default="RESEARCH", max_length=12)),
                ("idempotency_key", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("stage", models.CharField(default="queued", max_length=30)),
                ("cutoff", models.DateTimeField()),
                ("configuration_revision", models.PositiveIntegerField()),
                ("provider", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=160)),
                (
                    "prompt_version",
                    models.CharField(default="research-v1", max_length=40),
                ),
                ("context", models.JSONField(default=dict)),
                ("report", models.JSONField(null=True)),
                ("usage", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "market",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="markets.market",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "market", "-created_at"],
                        name="agents_agen_organiz_07bdc0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "idempotency_key"),
                        name="agent_request_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ["PENDING", "RUNNING"])),
                        fields=("organization",),
                        name="agent_one_active_per_org",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "PENDING",
                                    "RUNNING",
                                    "SUCCEEDED",
                                    "FAILED",
                                    "CANCELLED",
                                ],
                            )
                        ),
                        name="agent_valid_state",
                    ),
                ],
            },
        ),
    ]
