# Generated by Django 5.2.17 on 2026-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="language",
            field=models.CharField(default="en", max_length=2),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="reserved_calls",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="steps",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="workflow",
            field=models.CharField(default="single", max_length=20),
        ),
    ]
