# Generated by Django 5.2.17 on 2026-09-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_research_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="validation_errors",
            field=models.JSONField(default=list),
        ),
    ]
