# Generated by Django 5.2.17 on 2026-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_agentrun_assistant_graph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="assistant_name",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
