# Generated by Django 5.2.17 on 2026-09-20 11:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


def preserve_current_connections(apps, schema_editor):
    Configuration = apps.get_model("agents", "ModelConfiguration")
    Connection = apps.get_model("agents", "ModelConnection")
    alias = schema_editor.connection.alias
    for config in Configuration.objects.using(alias).filter(revision__gt=0).iterator():
        Connection.objects.using(alias).get_or_create(
            organization_id=config.organization_id,
            provider=config.provider,
            base_url=config.base_url.rstrip("/"),
            defaults={
                "model": config.model,
                "encrypted_api_key": config.encrypted_api_key,
                "max_output_tokens": config.max_output_tokens,
                "context_window_tokens": config.context_window_tokens,
                "enable_thinking": config.enable_thinking,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentrun_assistant_name'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('base_url', models.URLField(max_length=500)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('max_output_tokens', models.PositiveIntegerField(default=2000)),
                ('context_window_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('enable_thinking', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'base_url'), name='agent_connection_endpoint_unique')],
            },
        ),
        migrations.RunPython(preserve_current_connections, migrations.RunPython.noop),
    ]
