# Generated by Django 5.2.17 on 2026-09-15 15:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=1000)),
                (
                    "first_observed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceSource",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField(max_length=500)),
                ("last_checked_at", models.DateTimeField(null=True)),
                ("last_success_at", models.DateTimeField(null=True)),
                (
                    "next_poll_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("etag", models.CharField(blank=True, max_length=500)),
                ("last_modified", models.CharField(blank=True, max_length=200)),
                ("error", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "left",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_pairs",
                        to="markets.market",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_pairs",
                        to="markets.market",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComparisonReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(editable=False)),
                ("title", models.CharField(max_length=240)),
                ("topic", models.CharField(default="Macro & rates", max_length=80)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("EQUIVALENT", "Equivalent"),
                            ("RELATED", "Related with material differences"),
                            ("INCOMPATIBLE", "Incompatible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("SAME", "Same outcome"),
                            ("COMPLEMENT", "Complement of right outcome"),
                        ],
                        default="SAME",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("rationale", models.TextField()),
                (
                    "differences",
                    models.TextField(
                        help_text="Material wording, expiry, settlement, fee and liquidity differences."
                    ),
                ),
                ("left_snapshot", models.JSONField(editable=False)),
                ("right_snapshot", models.JSONField(editable=False)),
                ("reviewer_label", models.CharField(max_length=200)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="research.comparison",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TOPIC_ONLY", "Automatic topic association (unreviewed)"),
                            ("REVIEWED", "Reviewed relevance (not causality)"),
                            ("REJECTED", "Rejected association"),
                        ],
                        default="TOPIC_ONLY",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "method",
                    models.CharField(default="fed-topic-v1", editable=False, max_length=80),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="research.evidenceitem",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="markets.market",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=1000)),
                ("excerpt", models.TextField()),
                ("url", models.URLField(max_length=2000)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="research.evidenceitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="research.evidencesource",
            ),
        ),
        migrations.AddConstraint(
            model_name="comparison",
            constraint=models.CheckConstraint(
                condition=models.Q(("left", models.F("right")), _negated=True),
                name="pair_distinct",
            ),
        ),
        migrations.AddConstraint(
            model_name="comparison",
            constraint=models.UniqueConstraint(
                fields=("left", "right"), name="pair_endpoints_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="comparisonreview",
            constraint=models.UniqueConstraint(
                fields=("comparison", "version"), name="pair_review_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="comparisonreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="pair_confidence_range",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelink",
            index=models.Index(
                fields=["market", "item", "created_at"],
                name="research_ev_market__72d885_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencerevision",
            constraint=models.UniqueConstraint(fields=("item", "version"), name="evidence_version"),
        ),
        migrations.AddConstraint(
            model_name="evidenceitem",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="evidence_identity"
            ),
        ),
    ]
