# Generated by Django 5.2.17 on 2026-09-16 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenceitem",
            name="document_error",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="document_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="document_last_checked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="document_last_success_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="document_lease",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="document_next_poll_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="document",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="raw_document",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
