# Generated by Django 5.2.17 on 2026-09-16 15:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0002_collectionplan_researchtopic_collectiontarget"),
        ("research", "0002_official_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField(editable=False)),
                ("title", models.CharField(max_length=240)),
                ("title_zh", models.CharField(blank=True, max_length=240)),
                ("scope", models.TextField(max_length=3000)),
                ("scope_zh", models.TextField(blank=True, max_length=3000)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("calendar_url", models.URLField(max_length=1000)),
                (
                    "source_slugs",
                    models.JSONField(
                        help_text="Official feed IDs eligible for candidate matching."
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="research.eventdefinition",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.evidencerevision"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventEvidenceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Directly relevant / 直接相关"),
                            ("BACKGROUND", "Background only / 背景资料"),
                            ("UNRELATED", "Unrelated / 不相关"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(max_length=2000)),
                (
                    "paragraphs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="1–5 original paragraph numbers, e.g. [2, 4]. Required for direct relevance.",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="research.eventevidence",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="markets.researchtopic"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventMarketLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("snapshot", models.JSONField(editable=False)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_events",
                        to="markets.market",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_links",
                        to="research.researchevent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventdefinition",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to="research.researchevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventevidence",
            constraint=models.UniqueConstraint(
                fields=("definition", "revision"), name="event_evidence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventmarketlink",
            constraint=models.UniqueConstraint(
                fields=("event", "market"), name="event_market_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventdefinition",
            constraint=models.UniqueConstraint(
                fields=("event", "version"), name="event_definition_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))), name="event_date_order"
            ),
        ),
    ]
