# Generated by Django 5.2.17 on 2026-09-17 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0003_eventdefinition_eventevidence_eventevidencereview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencerevision",
            name="raw_feed_fields",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="last_duplicate_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="last_entry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="last_rejected_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="last_result",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="last_undated_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="latest_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="lease_expires_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="poll_interval_seconds",
            field=models.PositiveIntegerField(
                default=900,
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(86400),
                ],
            ),
        ),
        migrations.AddField(
            model_name="evidencesource",
            name="poll_lease",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="evidencesource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("poll_interval_seconds__gte", 300), ("poll_interval_seconds__lte", 86400)
                ),
                name="evidence_poll_interval_bounds",
            ),
        ),
    ]
