# Generated by Django 5.2.17 on 2026-09-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0004_curated_news_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="discovery_policy",
            field=models.CharField(
                choices=[
                    ("source-only-v1", "Selected official sources"),
                    ("fed-macro-v1", "Fed / US macro content and time window"),
                ],
                default="source-only-v1",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="eventevidence",
            name="discovery",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="eventevidence",
            name="discovery_priority",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="eventevidencereview",
            name="feed_quote",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="eventevidencereview",
            name="stance",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Undetermined / 无法判断"),
                    ("SUPPORTS", "Supports selected outcome / 支持所选结果"),
                    ("OPPOSES", "Opposes selected outcome / 反对所选结果"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="eventevidencereview",
            name="target_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="research.eventmarketlink",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="source_slugs",
            field=models.JSONField(
                help_text="Registered feed IDs eligible for candidate matching."
            ),
        ),
    ]
