# Generated by Django 5.2.17 on 2026-09-18 03:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0004_local_model_configuration"),
        ("markets", "0005_collection_bounds"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("strategy", models.CharField(max_length=30)),
                (
                    "initial_cash",
                    models.DecimalField(decimal_places=6, default=10000, max_digits=20),
                ),
                ("cash", models.DecimalField(decimal_places=6, default=10000, max_digits=20)),
                ("realized_pnl", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("fees", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("high_water", models.DecimalField(decimal_places=6, default=10000, max_digits=20)),
                ("max_drawdown", models.DecimalField(decimal_places=8, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("observation_id", models.UUIDField()),
                ("created_at", models.DateTimeField()),
                ("action", models.CharField(max_length=10)),
                ("reason", models.CharField(max_length=80)),
                ("inputs", models.JSONField(default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="paper.account",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="agents.agentrun"
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="markets.market"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("at", models.DateTimeField()),
                ("cash", models.DecimalField(decimal_places=6, max_digits=20)),
                ("equity", models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ("unrealized_pnl", models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ("realized_pnl", models.DecimalField(decimal_places=6, max_digits=20)),
                ("fees", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unpriced_positions", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equity",
                        to="paper.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="Paper trading experiment", max_length=120)),
                ("running", models.BooleanField(default=True)),
                ("version", models.CharField(default="paper-v1", max_length=30)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checked_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="paper.experiment",
            ),
        ),
        migrations.CreateModel(
            name="ExperimentMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rules_version", models.CharField(max_length=255)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="universe",
                        to="paper.experiment",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="markets.market"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("side", models.CharField(max_length=4)),
                ("status", models.CharField(default="PENDING", max_length=12)),
                ("reason", models.CharField(blank=True, max_length=80)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("limit_price", models.DecimalField(decimal_places=6, max_digits=12)),
                ("budget", models.DecimalField(decimal_places=6, max_digits=20)),
                ("eligible_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("execution_quote", models.JSONField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="paper.account",
                    ),
                ),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="paper.decision"
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="markets.market"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=12)),
                ("quantity", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("fee", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("cash_delta", models.DecimalField(decimal_places=6, max_digits=20)),
                ("realized_pnl", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("quote_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger",
                        to="paper.account",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="markets.market"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fills",
                        to="paper.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("cost_basis", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(null=True)),
                ("settlement_quote", models.JSONField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="paper.account",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="markets.market"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("account", "market", "observation_id"), name="paper_decision_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="equitysnapshot",
            index=models.Index(fields=["account", "at"], name="paper_equit_account_aa1d72_idx"),
        ),
        migrations.AddConstraint(
            model_name="equitysnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "at"), name="paper_equity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("experiment", "platform", "strategy"), name="paper_account_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("cash__gte", 0)), name="paper_cash_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="experimentmarket",
            constraint=models.UniqueConstraint(
                fields=("experiment", "market"), name="paper_universe_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("account", "market"),
                name="paper_one_pending_per_market",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="paper_order_positive_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("account", "market"), name="paper_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="paper_position_nonnegative"
            ),
        ),
    ]
