# Generated by Django 5.2.17 on 2026-09-18 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_agentrun_assistant_graph_and_more"),
        ("markets", "0005_collection_bounds"),
        ("organizations", "0001_initial"),
        ("paper", "0002_automatic_review_experiments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="paper_account_unique",
        ),
        migrations.RemoveConstraint(
            model_name="experiment",
            name="paper_version_unique",
        ),
        migrations.RemoveConstraint(
            model_name="opportunity",
            name="paper_opportunity_unique",
        ),
        migrations.RemoveConstraint(
            model_name="opportunity",
            name="paper_one_waiting_opportunity",
        ),
        migrations.AddField(
            model_name="account",
            name="assistant_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="agents.assistantversion",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="paper.account",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assistant_version__isnull", True)),
                fields=("experiment", "platform", "strategy"),
                name="paper_baseline_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assistant_version__isnull", False)),
                fields=("experiment", "platform", "assistant_version"),
                name="paper_assistant_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assistant_version__isnull", False), ("strategy", "assistant")),
                    models.Q(
                        models.Q(("strategy", "assistant"), _negated=True),
                        ("assistant_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="paper_assistant_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="experiment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version__in", ["paper-v1", "paper-v2"])),
                fields=("organization", "version"),
                name="paper_legacy_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", True)),
                fields=("experiment", "market", "observation_id"),
                name="paper_legacy_opportunity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", True), ("state", "WAITING")),
                fields=("experiment", "market"),
                name="paper_legacy_waiting_opportunity",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False)),
                fields=("account", "market", "observation_id"),
                name="paper_account_opportunity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False), ("state", "WAITING")),
                fields=("account", "market"),
                name="paper_account_waiting_unique",
            ),
        ),
    ]
